#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/Applications/nrn71_x86_64/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/Applications/nrn71_x86_64/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/Users/rspangler/school/computationalneuroscience/neuron/hh_zoo/x86_64/.libs/libnrnmech.so" "$@"
